version: '2.1'

services:
  kong-database:
    image: postgres:9.6.11-alpine
    container_name: kong-database
    volumes:
      - kong_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
    healthcheck:
      test: pg_isready -U kong && psql -d kong -U kong -c "SELECT 1=1"
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    build: ./kong
    container_name: kong-migration
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
    command: sh -c "(kong migrations up || kong migrations bootstrap) && touch migrations_run && sleep 30"
    healthcheck:
      test: "if [[ -f migrations_run ]] ; then exit 0; else exit 1; fi"
      interval: 10s
      timeout: 5s
      retries: 5

  kong:
    build: ./kong
    container_name: kong
    depends_on:
      kong-database:
        condition: service_healthy
    volumes:
      - ./dummy-plugin:/usr/local/bin/dummy-plugin
      - ./xml-request-transformer:/usr/local/bin/xml-request-transformer
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: dummy-plugin,basic-auth,prometheus,xml-request-transformer
      KONG_PLUGINSERVER_NAMES: dummy-plugin,xml-request-transformer
      KONG_PLUGINSERVER_DUMMY_PLUGIN_QUERY_CMD: /usr/local/bin/dummy-plugin -dump
      KONG_PLUGINSERVER_XML_REQUEST_TRANSFORMER_QUERY_CMD: /usr/local/bin/xml-request-transformer -dump
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
    healthcheck:
      test: kong health
      interval: 10s
      timeout: 5s
      retries: 5

  konga-database:
    image: mongo:4.1.5
    container_name: konga-database
    volumes:
      - konga_data:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/konga --quiet
      interval: 10s
      timeout: 5s
      retries: 5

#  kong-dashboard:
#    image: pgbi/kong-dashboard:v3
#    container_name: kong-dashboard
#    depends_on:
#      kong:
#        condition: service_healthy
#    command: start --kong-url http://kong:8001
#    ports:
#      - 8080:8080
#    restart: on-failure

  konga:
    build: ./konga
    container_name: konga
    depends_on:
      konga-database:
        condition: service_healthy
    volumes:
      - ./konga/user_seed.js:/app/user_seed.js:ro
    ports:
      - 1337:1337
    environment:
      DB_ADAPTER: mongo
      DB_DATABASE: konga
      DB_HOST: konga-database
      KONGA_SEED_USER_DATA_SOURCE_FILE: /app/user_seed.js
      NODE_ENV: production
    restart: on-failure

  servicea:
    build: ./servicea
    container_name: servicea
    ports:
      - 8085:8095

  serviceb:
    build: ./serviceb
    container_name: serviceb
    ports:
      - 8086:8086

  servicec:
    build: ./servicec
    container_name: servicec
    ports:
      - 8087:8087

volumes:
  kong_data:
  konga_data:
